"""refactor_courses_add_keycloak_course_id

Revision ID: 36316310ddb6
Revises: 40ac5b55f00c
Create Date: 2026-01-27 21:21:34.329163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36316310ddb6'
down_revision: Union[str, Sequence[str], None] = '40ac5b55f00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
