"""refactor_courses_table_add_keycloak_course_id

Revision ID: 40ac5b55f00c
Revises: 607a2e0c0bdd
Create Date: 2026-01-27 21:07:21.021440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ac5b55f00c'
down_revision: Union[str, Sequence[str], None] = '607a2e0c0bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('keycloak_course_id', sa.String(length=255), nullable=False, comment='Keycloak group ID for this course'))
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Course name',
               existing_nullable=False)
    op.create_unique_constraint(None, 'courses', ['keycloak_course_id'])
    op.drop_constraint(op.f('courses_lecturer_id_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'semester')
    op.drop_column('courses', 'lecturer_id')
    op.alter_column('deployments', 'course_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=36),
               comment='Course ID (auto-created from Keycloak course_id)',
               existing_comment='Keycloak group ID for the course',
               existing_nullable=False)
    op.create_foreign_key(None, 'deployments', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.alter_column('deployments', 'course_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=255),
               comment='Keycloak group ID for the course',
               existing_comment='Course ID (auto-created from Keycloak course_id)',
               existing_nullable=False)
    op.add_column('courses', sa.Column('lecturer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('semester', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('courses_lecturer_id_fkey'), 'courses', 'users', ['lecturer_id'], ['id'])
    op.drop_constraint(None, 'courses', type_='unique')
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Course name',
               existing_nullable=False)
    op.drop_column('courses', 'keycloak_course_id')
    # ### end Alembic commands ###
