"""remove_course_fk_and_deployment_mode_from_deployments

Revision ID: 607a2e0c0bdd
Revises: merge_deployment_branches
Create Date: 2026-01-27 20:00:33.958962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '607a2e0c0bdd'
down_revision: Union[str, Sequence[str], None] = 'merge_deployment_branches'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployments', 'course_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               comment='Keycloak group ID for the course',
               existing_nullable=False)
    op.alter_column('deployments', 'deployment_parameters',
               existing_type=sa.VARCHAR(),
               comment='Heat parameters, stack_assignments, and teacher info as JSON',
               existing_nullable=True)
    op.drop_constraint(op.f('deployments_course_id_fkey'), 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'access_types_json')
    op.drop_column('deployments', 'config_json')
    op.drop_column('deployments', 'deployment_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('deployment_mode', postgresql.ENUM('PER_COURSE', 'PER_GROUP', 'PER_STUDENT', name='deploymentmode'), autoincrement=False, nullable=False))
    op.add_column('deployments', sa.Column('config_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('access_types_json', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('deployments_course_id_fkey'), 'deployments', 'courses', ['course_id'], ['id'])
    op.alter_column('deployments', 'deployment_parameters',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Heat parameters, stack_assignments, and teacher info as JSON',
               existing_nullable=True)
    op.alter_column('deployments', 'course_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Keycloak group ID for the course',
               existing_nullable=False)
    # ### end Alembic commands ###
