"""Initial migration

Revision ID: c3eb8a110c7a
Revises: 
Create Date: 2026-01-12 10:23:44.387496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3eb8a110c7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('course_member_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('group_members_course_members_id_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'course_members', ['course_member_id'], ['id'])
    op.drop_column('group_members', 'course_members_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('course_members_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_course_members_id_fkey'), 'group_members', 'course_members', ['course_members_id'], ['id'])
    op.drop_column('group_members', 'course_member_id')
    # ### end Alembic commands ###
